require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - bin/*
    - .bundle/*
    - vendor/cache/**/*
    - db/seeds.rb
    - db/config/*

Metrics/LineLength:
  Max: 121

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  Enabled: false

MethodLength:
  Max: 15

Documentation:
  Enabled: false

PerlBackrefs:
  Enabled: false

StructInheritance:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - app/controllers/comments_controller.rb

Style/FrozenStringLiteralComment:
  Enabled: false

# we need 6 arguments for active support event subscribing
Metrics/ParameterLists:
  Max: 6

Performance/RedundantBlockCall:
  Enabled: false
